name: Game of life testing

on: push

jobs:
  game-of-life-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Maven version
        run: mvn --version
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Maven test
        run: mvn test

